# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoodosCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoodosCase
  pod 'TinyConstraints', '~> 4.0'
  pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher', :branch => 'version6-xcode13'
  pod 'Alamofire', '~> 5.4'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
  pod 'FirebaseRemoteConfig'
  pod 'lottie-ios'
  pod 'SwiftEntryKit', '2.0.0'
  pod 'FirebaseAnalytics'
end
